[package]
edition = "2021"
name = "dragonglass_render"
version = "0.1.0"

[dependencies]
dragonglass_dependencies = {path = "../dragonglass_dependencies"}
dragonglass_world = {path = "../dragonglass_world"}
